# Generated by Django 3.2.19 on 2023-06-10 17:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2023, 6, 11, 17, 50, 34, 707049, tzinfo=utc)),
        ),
    ]
